name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - "**"
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/**'

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  BuildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Ensure dependencies
        run: go mod tidy

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build ./...

      - name: Pull Containers
        run: docker compose pull

      - name: Start Containers
        run: docker compose up -d

      - name: Run Tests
        run: go test ./... -v

      - name: Stop Containers
        if: always()
        run: docker compose down --volumes
