name: Pre-Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write
  packages: read

jobs:
  TagAndPublish:
    name: Tag and Notify Go Proxy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Full History
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.0.1

      - name: Calculate Version
        id: version
        uses: gittools/actions/gitversion/execute@v4.0.1

      - name: Tag Commit
        uses: fgrzl/actions/tag-commit@v1
        with:
          tag: ${{ steps.version.outputs.semVer }}

      - name: Notify Go Proxy
        uses: fgrzl/actions/notify-go-proxy@v1
        with:
          tag: ${{ steps.version.outputs.semVer }}

      - name: Prune Pre-release Tags
        uses: fgrzl/actions/cleanup-old-prerelease-tags@v1
